// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.32.1
// source: apps/common/proto/user.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { wrappers } from "protobufjs";
import { Observable } from "rxjs";
import { Struct } from "../../../google/protobuf/struct";

export const protobufPackage = "user";

/** Request para guardar un nuevo usuario */
export interface SaveUserRequest {
  user: User | undefined;
}

/** Response al guardar usuario */
export interface SaveUserResponse {
  /** Indica si se guardó correctamente */
  success: boolean;
  /** Mensaje descriptivo */
  message: string;
  /** Usuario guardado (opcional) */
  user: User | undefined;
}

export interface User {
  id: string;
  email: string;
  firstName: string;
  paternalLastName: string;
  maternalLastName: string;
  birthdate: string;
  dni: string;
  phone: string;
  role: string;
  avatar: string;
  metadata: Struct ;
}

export interface VerifyDNIRequest {
  dni: string;
}

export interface VerifyDNIResponse {
  isValid: boolean;
}

export interface VerifyEmailRequest {
  email: string;
}

export interface VerifyEmailResponse {
  isValid: boolean;
}

export const USER_PACKAGE_NAME = "user";

wrappers[".google.protobuf.Struct"] = { fromObject: Struct.wrap, toObject: Struct.unwrap } as any;

export interface UserServiceClient {
  saveUser(request: SaveUserRequest): Observable<SaveUserResponse>;

  verifyDni(request: VerifyDNIRequest): Observable<VerifyDNIResponse>;

  verifyEmail(request: VerifyEmailRequest): Observable<VerifyEmailResponse>;
}

export interface UserServiceController {
  saveUser(request: SaveUserRequest): Promise<SaveUserResponse> | Observable<SaveUserResponse> | SaveUserResponse;

  verifyDni(request: VerifyDNIRequest): Promise<VerifyDNIResponse> | Observable<VerifyDNIResponse> | VerifyDNIResponse;

  verifyEmail(
    request: VerifyEmailRequest,
  ): Promise<VerifyEmailResponse> | Observable<VerifyEmailResponse> | VerifyEmailResponse;
}

export function UserServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["saveUser", "verifyDni", "verifyEmail"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("UserService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("UserService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const USER_SERVICE_NAME = "UserService";
